TicTacToeWeb/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;

namespace TicTacToeWeb.Controllers
{
    public class SettingsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TicTacToeWeb/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TicTacToe.Common.Constants;
using TicTacToe.Services.Interfaces;

namespace TicTacToeWeb.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;

        public UserController(IUserService userService)
        {
            this.userService = userService;
        }

        [HttpGet]
        [Authorize(Roles = RoleConstants.PLAYER_ROLE)]
        public IActionResult All()
        {
            var model = userService.GetAllUsers();
            return View(model);
        }

        public IActionResult Details(string userId)
        {
            return null;
        }
    }
}

TicTacToeWeb/Views/Shared/_GameListPartial.cshtml
@model IList<GameInfoViewModel>

<table class="table table-striped">
    <thead>
    <tr>
        <th style="width: 35px">#</th>
        <th style="width: 135px"> Description</th>
        <th style="width: 100px"> Creator</th>
        <th style="width: 100px"> Visibility</th>
        <th style="width: 135px"> Created On</th>
        <th style="width: 135px"> Status</th>
        <th style="width: 60px"> </th>
    </tr>
    </thead>

    <tbody >
        @(Html.DisplayForModel("GameInfoViewModel"))
    </tbody>
</table>

TicTacToeWeb/Views/Shared/_GamesPartial.cshtml
@model GameIndexViewModel

@if (Model.UserGamesInProgress.Count != 0)
{
    <div class="row">
        <h2>Games in progress</h2>

        @await Html.PartialAsync("_GameListPartial", Model.UserGamesInProgress.ToList())
    </div>
}
    
@if (Model.UserJoinedGames.Count != 0)
{
    <div class="row">
        <h2>Joined games</h2>
        @await Html.PartialAsync("_GameListPartial", Model.UserJoinedGames.ToList())
    </div>
}

@if (Model.AvailableGames.Count != 0)
{
    <div class="row">
        <h2>Available Games</h2>
        @await Html.PartialAsync("_GameListPartial", Model.AvailableGames.ToList())
    </div>
}

TicTacToeWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TicTacToe</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/game-grid.css" />
        <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color: #003d70e3">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Game" asp-action="Index" class="navbar-brand">TicTacToeWeb</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Game" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-page="/Scores">Scores</a></li>
                    <li><a asp-area="" asp-page="/History">History</a></li>
                    <li><a asp-area="" asp-controller="User" asp-action="All">Users</a></li>
                    <li><a asp-area="" asp-controller="Settings" asp-action="Index">Settings</a></li>
                    <li><a asp-area="" asp-page="/About">About</a></li>
                    <li><a asp-area="" asp-page="/FeedBack">FeedBack</a></li>
                </ul>
                

                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - TicTacToeWeb</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/toastr/toastr.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>